### ISSUE TITLE
unable to run the program

### ISSUE THREAD

**Issue by ankushgoel27** [secxena/credcheck#3]
seeing this error

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from credcheck.core.cred_check_utils import CredUtils
  File "/opt/credcheck/credcheck/core/__init__.py", line 1, in <module>
    from .cred_check_active import DynamicTest
  File "/opt/credcheck/credcheck/core/cred_check_active.py", line 3, in <module>
    from credcheck.core.cred_check_utils import CredUtils
  File "/opt/credcheck/credcheck/core/cred_check_utils.py", line 81
    raise ParametersRequiredError(_helper.get("help"), _helper) from None
                                                                   ^
SyntaxError: invalid syntax

**Comment by secxena** [comment]
are you running it using python 2.7.* ?

**Comment by secxena** [comment]
Run it using 3.6+, it should work. @ankushgoel27
